version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: taxi-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  driver-service:
    build: ./driver-service
    container_name: driver-service
    #ports:
    #  - "8081:8081"
    expose:
      - "8081"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017"
      DB_NAME: "taxihub"
      PORT: "8081"
      GIN_MODE: "debug"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - driver-service
    environment:
      PORT: "8080"
      DRIVER_SERVICE_URL: "http://driver-service:8081"
      JWT_SECRET: "your-super-secret-jwt-key"
      API_KEY: "admin-api-key-12345"
      RATE_LIMIT_RPS: "10"
      GIN_MODE: "debug"
      LOG_LEVEL: "info"
      LOG_FORMAT: "json"
      ENABLE_FILE_LOG: "true"

volumes:
  mongo-data:
